/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#e5e2e3",
        "on-primary": "#00363a",
        "surface-dim": "#131314",
        "surface": "#131314",
        "secondary-fixed-dim": "#ebb2ff",
        "error-container": "#93000a",
        "primary": "#dbfcff",
        "on-tertiary-container": "#5f5e60",
        "primary-container": "#00f0ff",
        "inverse-surface": "#e5e2e3",
        "tertiary-container": "#dbd8db",
        "primary-fixed-dim": "#00dbe9",
        "tertiary-fixed": "#e4e2e4",
        "on-tertiary-fixed": "#1b1b1d",
        "surface-container-high": "#2a2a2b",
        "surface-container-highest": "#353436",
        "on-surface-variant": "#b9cacb",
        "inverse-on-surface": "#313031",
        "tertiary": "#f8f4f7",
        "on-secondary": "#520072",
        "on-primary-fixed": "#002022",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#74009f",
        "on-primary-fixed-variant": "#004f54",
        "on-secondary-container": "#fff6fc",
        "error": "#ffb4ab",
        "surface-container-lowest": "#0e0e0f",
        "primary-fixed": "#7df4ff",
        "surface-bright": "#3a393a",
        "on-surface": "#e5e2e3",
        "outline-variant": "#3b494b",
        "background": "#131314",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#f8d8ff",
        "surface-variant": "#353436",
        "secondary": "#ebb2ff",
        "on-tertiary": "#303032",
        "surface-tint": "#00dbe9",
        "secondary-container": "#b600f8",
        "on-secondary-fixed": "#320047",
        "outline": "#849495",
        "on-tertiary-fixed-variant": "#474649",
        "surface-container-low": "#1c1b1c",
        "on-primary-container": "#006970",
        "inverse-primary": "#006970",
        "tertiary-fixed-dim": "#c8c6c8",
        "surface-container": "#201f20"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "lg": "24px",
        "xxl": "64px",
        "gutter": "24px",
        "xl": "40px",
        "xs": "4px",
        "md": "16px",
        "unit": "4px",
        "margin": "32px",
        "sm": "8px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-md": ["Space Grotesk"],
        "mono-data": ["Space Grotesk"],
        "label-caps": ["Space Grotesk"],
        "headline-xl": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"]
      }
    },
  },
  plugins: [],
}
